user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults:
        _format: json

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group